[tool.poetry]
name = "thirdweb-sdk"
version = "1.0.0"
description = ""
authors = ["adam-maj <mr.adam.maj@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
eth-brownie = "^1.18.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
