[tool.poetry]
name = "thirdweb-sdk"
version = "2.0.0"
description = ""
authors = ["thirdweb <sdk@thirdweb.com>"]

[tool.poetry.dependencies]
python = ">3.7.1,<3.10"
0x-contract-wrappers = "^2.0.0"
web3 = "5.27.0"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
mypy = "^0.941"
pylint = "^2.12.2"
eth-brownie = "^1.18.1"
types-requests = "^2.27.14"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
