[tool.poetry]
name = "thirdweb-sdk"
version = "1.0.0"
description = ""
authors = ["adam-maj <mr.adam.maj@gmail.com>"]

[tool.poetry.dependencies]
python = ">3.7.1,<3.10"
eth-brownie = "^1.18.1"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
mypy = "^0.941"
pylint = "^2.12.2"

[mypy]
python = ">3.7.1,<3.10"
exclude = "*.py"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"