docs_dir: content
nav:
- ThirdwebSDK: api-reference/core/sdk.md
- NFT Collection: api-reference/contracts/nft-collection.md
- Edition: api-reference/contracts/edition.md
- Token: api-reference/contracts/token.md
- Marketplace: api-reference/contracts/marketplace.md
- NFT Drop: api-reference/contracts/nft-drop.md
- ERC20 Signature Minting: api-reference/core/classes/erc20-signature-minting.md
- ERC721 Signature Minting: api-reference/core/classes/erc721-signature-minting.md
- ERC1155 Signature Minting: api-reference/core/classes/erc1155-signature-minting.md
- Marketplace Direct: api-reference/core/classes/marketplace-direct.md
- Marketplace Auction: api-reference/core/classes/marketplace-auction.md
- Contract Metadata: api-reference/core/classes/contract-metadata.md
- Contract Platform Fee: api-reference/core/classes/contract-platform-fee.md
- Contract Royalty: api-reference/core/classes/contract-royalty.md
- Contract Sales: api-reference/core/classes/contract-sales.md
- Drop Claim Conditions: api-reference/core/classes/drop-claim-conditions.md
- ERC20: api-reference/core/classes/erc20.md
- ERC721: api-reference/core/classes/erc721.md
- ERC1155: api-reference/core/classes/erc1155.md
- ERC20: api-reference/core/classes/erc20.md
- Contract Deployer: api-reference/core/classes/contract-deployer.md
- Contract Roles: api-reference/core/classes/contract-roles.md
site_name: Thirdweb Python SDK
theme:
  extra:
    social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/thirdweb_
    - icon: fontawesome/brands/discord
      link: https://discord.gg/thirdweb
  extra_css:
  - css/autodoc.css
  favicon: images/logo.png
  features:
  - navigation.tracking
  - navigation.indexes
  - navigation.top
  - navigation.instant
  logo: images/logo.png
  markdown_extensions:
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  name: material
  palette:
  - primary: black
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - primary: black
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: restructured-text
          setup_commands:
          - import sys
          - sys.path.append('../')
