site_name: Thirdweb Python SDK

theme:
  logo: images/logo.png
  favicon: images/logo.png
  name: material
  features:
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - navigation.instant
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - "Getting Started": "index.md"
  - "API Reference":
    - "ThirdwebSDK": "api-reference/core/sdk.md"
    - "Contracts":
      - "NFT Collection": "api-reference/contracts/nft-collection.md"
      - "Edition": "api-reference/contracts/edition.md"
      - "Token": "api-reference/contracts/token.md"
      - "Marketplace": "api-reference/contracts/marketplace.md"
    - "Core Interfaces":
      - "Contract Intefaces"
        - "ERC20": "api-reference/core/classes/erc20.md"
        - "ERC721": "api-reference/core/classes/erc721.md"
        - "ERC1155": "api-reference/core/classes/erc1155.md"
      - "Signature Minting":
        - "ERC20 Signature Minting": "api-reference/core/classes/erc20-signature-minting.md"
        - "ERC721 Signature Minting": "api-reference/core/classes/erc721-signature-minting.md"
        - "ERC1155 Signature Minting": ""api-reference/core/classes/erc1155-signature-minting.md"" 
      - "Marketplace Listings"
        - "Marketplace Direct": "api-reference/core/classes/marketplace-direct.md"
        - "Marketplace Auction": "api-reference/core/classes/marketplace-auction.md"
      - "Contract Settings":
        - "Contract Metadata": "api-reference/core/classes/contract-metadata.md"
        - "Contract Platform Fee": "api-reference/core/classes/contract-platform-fee.md"
        - "Contract Royalty": "api-reference/core/classes/contract-royalty.md"
        - "Contract Sales": "api-reference/core/classes/contract-sales.md"
      - "Contract Deployer": "api-reference/core/classes/contract-deployer.md"
      - "Contract Roles": "api-reference/core/classes/contract-roles.md"
markdown_extensions:
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets

extra_css:
  - css/autodoc.css

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: restructured-text
          setup_commands:
            - import sys
            - sys.path.append('../')

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/thirdweb_
    - icon: fontawesome/brands/discord
      link: https://discord.gg/thirdweb